services:
  - type: web
    name: gan-dener-client
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production